// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: example.sql

package example

import (
	"context"
)

const findAllExample = `-- name: FindAllExample :many
SELECT id, name, description, created_at, updated_at FROM examples
`

func (q *Queries) FindAllExample(ctx context.Context) ([]Example, error) {
	rows, err := q.db.Query(ctx, findAllExample)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
