// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package example

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Example struct {
	ID          int32
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
